name: 'Stable Deploy CI (Maven)'

on:
  push

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/stable/')
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Remove snapshots
        run: mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn -DskipTests -Dcheckstyle.skip=true package

      - name: Calculate tag
        id: tagcalc
        run: |
          tag=$(grep "version=" airsonic-main/target/generated/build-metadata/build.properties | cut -d"=" -f2)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagcalc.outputs.tag }}
          name: Stable Release ${{ steps.tagcalc.outputs.tag }}
          draft: true
          prerelease: false
          generate_release_notes: true
          body: |
            List of issues addressed: https://github.com/kagemomiji/airsonic-advanced/issues?q=milestone%3A${{ steps.tagcalc.outputs.tag }}
          files: |
            airsonic-main/target/airsonic.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
